# Generated by Django 5.1.7 on 2025-03-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customlogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomLogEntry',
        ),
    ]
