# Generated by Django 5.1.7 on 2025-04-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_customlogentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantowner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='restaurant_address',
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='restaurant_name',
        ),
    ]
