# Generated by Django 5.1.7 on 2025-04-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_restaurantowner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
